name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.2'
          cache: true
      - uses: actions/checkout@v4

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6.1.1
        with:
          version: latest

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.2'
          cache: true

      - name: Install dependencies
        run: go mod tidy

      - name: Build for Windows
        run: |
          GOOS=windows GOARCH=amd64 go build

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: todolist-exe
          path: todolist.exe

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.2'
          cache: true

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests and generate report
        run: |
          go test -json ./tests | go-test-report -o test_report.html
          
      - name: Upload test report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test_report.html
